version: '3.8'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: grocery_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 123india
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASS: password
      DB_NAME: grocery_db
      JWT_SECRET: your_secret_key
    ports:
      - "5000:5000"

volumes:
  mysql_data:
